**This is the code to extract Census data for the year 2016.**
The data fields are:
County
Population
Median Age
Household Income
Per Capita Income
Poverty Count
Poverty Rate
White
Black or African American
American Indian or Alaska Native
Asian
Hawaiian or Other Pacific Islander
Less Than High School
High School
Some College or Associate's Degree
Bachelor's Degree
Graduate or Professional Degree

In [28]:
 # Dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
import seaborn as sns
from census import Census
from us import states

import matplotlib.pyplot as plt

enable Python to display matplotlib graphs
%matplotlib inline

# Census API Key
#from config import census_api
c = Census("5611b27a0e676d84191f3b77bcc3089a1874fdbd", year = 2016)
#print(census_api)

In [29]:
# Run Census Search to retrieve data on Itasca county within Minnesota
census_data = c.acs5.get(("NAME", "B01003_001E", "B01002_001E", "B19013_001E", "B19301_001E", 
                          "B17001_002E", "B02001_002E", "B02001_003E", "B02001_004E", "B02001_005E", "B02001_006E",  
                         "B06009_002E", "B06009_003E", "B06009_004E", "B06009_005E", "B06009_006E"), 
                         {'for': 'county: 061', 'in': 'state: 27'})

# Convert to DataFrame
census_Itasca = pd.DataFrame(census_data)

# Column Reordering
census_Itasca = census_Itasca.rename(columns={"B01003_001E": "Population", "B01002_001E": "Median Age", 
                                      "B19013_001E": "Household Income", "B19301_001E": "Per Capita Income", 
                                      "B17001_002E": "Poverty Count", 
                                      "B02001_002E": "White", "B02001_003E": "Black or African American", 
                                      "B02001_004E": "American Indian or Alaska Native", "B02001_005E": "Asian", 
                                      "B02001_006E": "Hawaiian or Other Pacific Islander", 
                                      "B06009_002E": "Less Than High School", "B06009_003E": "High School", 
                                      "B06009_004E": "Some College or Associate's Degree", 
                                      "B06009_005E": "Bachelor's Degree", "B06009_006E": "Graduate or Professional Degree",
                                      "state": "State", "NAME": "County"})

# Poverty Rate (Poverty Count / Population)
census_Itasca["Poverty Rate"] = 100 * \
    census_Itasca["Poverty Count"].astype(
        int) / census_Itasca["Population"].astype(int)


# Final DataFrame
census_Itasca = census_Itasca[["State", "County", "Population", "Median Age", "Household Income", 
                       "Per Capita Income", "Poverty Count", "Poverty Rate", 
                       "White", "Black or African American", "American Indian or Alaska Native",
                       "Asian", "Hawaiian or Other Pacific Islander",
                       "Less Than High School", "High School", "Some College or Associate's Degree", 
                       "Bachelor's Degree", "Graduate or Professional Degree"]]

census_Itasca.head()

,State,County,Population,Median Age,Household Income,Per Capita Income,Poverty Count,Poverty Rate,White,Black or African American,American Indian or Alaska Native,Asian,Hawaiian or Other Pacific Islander,Less Than High School,High School,Some College or Associate's Degree,Bachelor's Degree,Graduate or Professional Degree
0,27,"Itasca County, Minnesota",45356.0,45.9,49507.0,25862.0,5886.0,12.977335,42163.0,224.0,1594.0,191.0,5.0,2179.0,10071.0,13023.0,4900.0,2335.0

In [30]:
# Run Census Search to retrieve data on Hennepin county within Minnesota
census_data = c.acs5.get(("NAME", "B01003_001E", "B01002_001E", "B19013_001E", "B19301_001E", 
                          "B17001_002E", "B02001_002E", "B02001_003E", "B02001_004E", "B02001_005E", "B02001_006E",  
                         "B06009_002E", "B06009_003E", "B06009_004E", "B06009_005E", "B06009_006E"), 
                         {'for': 'county: 053', 'in': 'state: 27'})

# Convert to DataFrame
census_Hennepin = pd.DataFrame(census_data)

# Column Reordering
census_Hennepin = census_Hennepin.rename(columns={"B01003_001E": "Population", "B01002_001E": "Median Age", 
                                      "B19013_001E": "Household Income", "B19301_001E": "Per Capita Income", 
                                      "B17001_002E": "Poverty Count", 
                                      "B02001_002E": "White", "B02001_003E": "Black or African American", 
                                      "B02001_004E": "American Indian or Alaska Native", "B02001_005E": "Asian", 
                                      "B02001_006E": "Hawaiian or Other Pacific Islander", 
                                      "B06009_002E": "Less Than High School", "B06009_003E": "High School", 
                                      "B06009_004E": "Some College or Associate's Degree", 
                                      "B06009_005E": "Bachelor's Degree", "B06009_006E": "Graduate or Professional Degree",
                                      "state": "State", "NAME": "County"})

# Poverty Rate (Poverty Count / Population)
census_Hennepin["Poverty Rate"] = 100 * \
    census_Hennepin["Poverty Count"].astype(
        int) / census_Hennepin["Population"].astype(int)


# Final DataFrame
census_Hennepin = census_Hennepin[["State", "County", "Population", "Median Age", "Household Income", 
                       "Per Capita Income", "Poverty Count", "Poverty Rate", 
                       "White", "Black or African American", "American Indian or Alaska Native",
                       "Asian", "Hawaiian or Other Pacific Islander",
                       "Less Than High School", "High School", "Some College or Associate's Degree", 
                       "Bachelor's Degree", "Graduate or Professional Degree"]]

census_Hennepin.head()

,State,County,Population,Median Age,Household Income,Per Capita Income,Poverty Count,Poverty Rate,White,Black or African American,American Indian or Alaska Native,Asian,Hawaiian or Other Pacific Islander,Less Than High School,High School,Some College or Associate's Degree,Bachelor's Degree,Graduate or Professional Degree
0,27,"Hennepin County, Minnesota",1209265.0,36.2,67989.0,39939.0,141453.0,11.697436,891912.0,150522.0,7999.0,83228.0,487.0,59660.0,145576.0,230709.0,254187.0,141528.0

In [31]:
# Run Census Search to retrieve data on Ramsey county within Minnesota
census_data = c.acs5.get(("NAME", "B01003_001E", "B01002_001E", "B19013_001E", "B19301_001E", 
                          "B17001_002E", "B02001_002E", "B02001_003E", "B02001_004E", "B02001_005E", "B02001_006E",  
                         "B06009_002E", "B06009_003E", "B06009_004E", "B06009_005E", "B06009_006E"), 
                         {'for': 'county: 123', 'in': 'state: 27'})

# Convert to DataFrame
census_Ramsey = pd.DataFrame(census_data)

# Column Reordering
census_Ramsey = census_Ramsey.rename(columns={"B01003_001E": "Population", "B01002_001E": "Median Age", 
                                      "B19013_001E": "Household Income", "B19301_001E": "Per Capita Income", 
                                      "B17001_002E": "Poverty Count", 
                                      "B02001_002E": "White", "B02001_003E": "Black or African American", 
                                      "B02001_004E": "American Indian or Alaska Native", "B02001_005E": "Asian", 
                                      "B02001_006E": "Hawaiian or Other Pacific Islander", 
                                      "B06009_002E": "Less Than High School", "B06009_003E": "High School", 
                                      "B06009_004E": "Some College or Associate's Degree", 
                                      "B06009_005E": "Bachelor's Degree", "B06009_006E": "Graduate or Professional Degree",
                                      "state": "State", "NAME": "County"})

# Poverty Rate (Poverty Count / Population)
census_Ramsey["Poverty Rate"] = 100 * \
    census_Ramsey["Poverty Count"].astype(
        int) / census_Ramsey["Population"].astype(int)


# Final DataFrame
census_Ramsey = census_Ramsey[["State", "County", "Population", "Median Age", "Household Income", 
                       "Per Capita Income", "Poverty Count", "Poverty Rate", 
                       "White", "Black or African American", "American Indian or Alaska Native",
                       "Asian", "Hawaiian or Other Pacific Islander",
                       "Less Than High School", "High School", "Some College or Associate's Degree", 
                       "Bachelor's Degree", "Graduate or Professional Degree"]]

census_Ramsey.head()

,State,County,Population,Median Age,Household Income,Per Capita Income,Poverty Count,Poverty Rate,White,Black or African American,American Indian or Alaska Native,Asian,Hawaiian or Other Pacific Islander,Less Than High School,High School,Some College or Associate's Degree,Bachelor's Degree,Graduate or Professional Degree
0,27,"Ramsey County, Minnesota",531528.0,34.6,57717.0,31256.0,82252.0,15.474632,363250.0,59572.0,3401.0,72239.0,174.0,33973.0,76483.0,96009.0,86357.0,57132.0

In [32]:
# Run Census Search to retrieve data on Stearns county within Minnesota
census_data = c.acs5.get(("NAME", "B01003_001E", "B01002_001E", "B19013_001E", "B19301_001E", 
                          "B17001_002E", "B02001_002E", "B02001_003E", "B02001_004E", "B02001_005E", "B02001_006E",  
                         "B06009_002E", "B06009_003E", "B06009_004E", "B06009_005E", "B06009_006E"), 
                         {'for': 'county: 145', 'in': 'state: 27'})

# Convert to DataFrame
census_Stearns = pd.DataFrame(census_data)

# Column Reordering
census_Stearns = census_Stearns.rename(columns={"B01003_001E": "Population", "B01002_001E": "Median Age", 
                                      "B19013_001E": "Household Income", "B19301_001E": "Per Capita Income", 
                                      "B17001_002E": "Poverty Count", 
                                      "B02001_002E": "White", "B02001_003E": "Black or African American", 
                                      "B02001_004E": "American Indian or Alaska Native", "B02001_005E": "Asian", 
                                      "B02001_006E": "Hawaiian or Other Pacific Islander", 
                                      "B06009_002E": "Less Than High School", "B06009_003E": "High School", 
                                      "B06009_004E": "Some College or Associate's Degree", 
                                      "B06009_005E": "Bachelor's Degree", "B06009_006E": "Graduate or Professional Degree",
                                      "state": "State", "NAME": "County"})

# Poverty Rate (Poverty Count / Population)
census_Stearns["Poverty Rate"] = 100 * \
    census_Stearns["Poverty Count"].astype(
        int) / census_Stearns["Population"].astype(int)


# Final DataFrame
census_Stearns = census_Stearns[["State", "County", "Population", "Median Age", "Household Income", 
                       "Per Capita Income", "Poverty Count", "Poverty Rate", 
                       "White", "Black or African American", "American Indian or Alaska Native",
                       "Asian", "Hawaiian or Other Pacific Islander",
                       "Less Than High School", "High School", "Some College or Associate's Degree", 
                       "Bachelor's Degree", "Graduate or Professional Degree"]]

census_Stearns.head()

,State,County,Population,Median Age,Household Income,Per Capita Income,Poverty Count,Poverty Rate,White,Black or African American,American Indian or Alaska Native,Asian,Hawaiian or Other Pacific Islander,Less Than High School,High School,Some College or Associate's Degree,Bachelor's Degree,Graduate or Professional Degree
0,27,"Stearns County, Minnesota",153661.0,34.1,56977.0,27792.0,19983.0,13.004601,138458.0,6908.0,537.0,3064.0,22.0,7480.0,28170.0,34290.0,16838.0,7670.0

In [34]:
# Run Census Search to retrieve data on Steele county within Minnesota
census_data = c.acs5.get(("NAME", "B01003_001E", "B01002_001E", "B19013_001E", "B19301_001E", 
                          "B17001_002E", "B02001_002E", "B02001_003E", "B02001_004E", "B02001_005E", "B02001_006E",  
                         "B06009_002E", "B06009_003E", "B06009_004E", "B06009_005E", "B06009_006E"), 
                         {'for': 'county: 147', 'in': 'state: 27'})

# Convert to DataFrame
census_Steele = pd.DataFrame(census_data)

# Column Reordering
census_Steele = census_Steele.rename(columns={"B01003_001E": "Population", "B01002_001E": "Median Age", 
                                      "B19013_001E": "Household Income", "B19301_001E": "Per Capita Income", 
                                      "B17001_002E": "Poverty Count", 
                                      "B02001_002E": "White", "B02001_003E": "Black or African American", 
                                      "B02001_004E": "American Indian or Alaska Native", "B02001_005E": "Asian", 
                                      "B02001_006E": "Hawaiian or Other Pacific Islander", 
                                      "B06009_002E": "Less Than High School", "B06009_003E": "High School", 
                                      "B06009_004E": "Some College or Associate's Degree", 
                                      "B06009_005E": "Bachelor's Degree", "B06009_006E": "Graduate or Professional Degree",
                                      "state": "State", "NAME": "County"})

# Poverty Rate (Poverty Count / Population)
census_Steele["Poverty Rate"] = 100 * \
    census_Steele["Poverty Count"].astype(
        int) / census_Steele["Population"].astype(int)


# Final DataFrame
census_Steele = census_Steele[["State", "County", "Population", "Median Age", "Household Income", 
                       "Per Capita Income", "Poverty Count", "Poverty Rate", 
                       "White", "Black or African American", "American Indian or Alaska Native",
                       "Asian", "Hawaiian or Other Pacific Islander",
                       "Less Than High School", "High School", "Some College or Associate's Degree", 
                       "Bachelor's Degree", "Graduate or Professional Degree"]]

census_Steele.head()

,State,County,Population,Median Age,Household Income,Per Capita Income,Poverty Count,Poverty Rate,White,Black or African American,American Indian or Alaska Native,Asian,Hawaiian or Other Pacific Islander,Less Than High School,High School,Some College or Associate's Degree,Bachelor's Degree,Graduate or Professional Degree
0,27,"Steele County, Minnesota",36541.0,39.5,58141.0,28736.0,3396.0,9.29367,33101.0,1079.0,50.0,433.0,5.0,1857.0,8695.0,7794.0,4432.0,1614.0

In [37]:
# Float formating
pd.options.display.float_format = '{:,}'.format
pd.options.display.float_format = '{:,.1f}'.format

# Combining dataframes of all counties into one dataframe
combined = pd.concat([census_Itasca, census_Hennepin, census_Ramsey, census_Stearns, census_Steele], axis=0, sort=False, join='inner')
combined_df_2016 = pd.DataFrame(combined)

combined_df_2016

,State,County,Population,Median Age,Household Income,Per Capita Income,Poverty Count,Poverty Rate,White,Black or African American,American Indian or Alaska Native,Asian,Hawaiian or Other Pacific Islander,Less Than High School,High School,Some College or Associate's Degree,Bachelor's Degree,Graduate or Professional Degree
0,27,"Itasca County, Minnesota","45,356.0",45.9,"49,507.0","25,862.0","5,886.0",13.0,"42,163.0",224.0,"1,594.0",191.0,5.0,"2,179.0","10,071.0","13,023.0","4,900.0","2,335.0"
0,27,"Hennepin County, Minnesota","1,209,265.0",36.2,"67,989.0","39,939.0","141,453.0",11.7,"891,912.0","150,522.0","7,999.0","83,228.0",487.0,"59,660.0","145,576.0","230,709.0","254,187.0","141,528.0"
0,27,"Ramsey County, Minnesota","531,528.0",34.6,"57,717.0","31,256.0","82,252.0",15.5,"363,250.0","59,572.0","3,401.0","72,239.0",174.0,"33,973.0","76,483.0","96,009.0","86,357.0","57,132.0"
0,27,"Stearns County, Minnesota","153,661.0",34.1,"56,977.0","27,792.0","19,983.0",13.0,"138,458.0","6,908.0",537.0,"3,064.0",22.0,"7,480.0","28,170.0","34,290.0","16,838.0","7,670.0"
0,27,"Steele County, Minnesota","36,541.0",39.5,"58,141.0","28,736.0","3,396.0",9.3,"33,101.0","1,079.0",50.0,433.0,5.0,"1,857.0","8,695.0","7,794.0","4,432.0","1,614.0"

In [38]:
combined_df_2016.to_csv("census_data_2016.csv",index=False,header=True)